cc_binary(
    name = "ingest_file",
    srcs = ["ingest_file.cpp"],
    deps = [
        "//optimizer:PTree",
        "//optimizer:Predictor",
    ],
    data = [
        "//data:crackstation-human-only.txt",
    ],
)
